name: Check for README.md and LISEZMOI.md

on:
  push:
  workflow_dispatch:

jobs:
  readme-check:
    runs-on: ubuntu-latest
    steps:
    - name: Get list of repos
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        result=`curl -H "Authorization: $TOKEN" -H "Accept: application/vnd.github.v3+json" https://api.github.com/orgs/OpenDRR/repos?per_page=100 | jq .[].name | tr -d \"`
        for i in "${result[@]}"
        do
          if [ $EXISTING_BRANCH == 0 ];
          then
            code=`curl --write-out "%{http_code}\n" --output /dev/null --silent "https://api.github.com/repos/OpenDRR/$i/contents/README.md"`
            echo $i
            echo $code
          fi
          
        done
          
      #HTTP_CODE2=`curl --write-out "%{http_code}\n" "https://github.com/OpenDRR/${i}/blob/main/LISEZMOI.md" --output /dev/null --silent`
      #   echo $HTTP_CODE2