name: Check for README.md and LISEZMOI.md

on:
  push:
  workflow_dispatch:

jobs:
  readme-check:
    runs-on: ubuntu-latest
    steps:
    - name: Get list of repos
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        result=`curl -H "Authorization: $TOKEN" -H "Accept: application/vnd.github.v3+json" https://api.github.com/orgs/OpenDRR/repos?per_page=100 | jq .[].name | tr -d \"`
        for i in "${result[@]}"
        do
      #HTTP_CODE=`curl --write-out "%{http_code}\n" "https://github.com/OpenDRR/${i}/blob/main/README.md" --output /dev/null --silent`
          echo $i
      #HTTP_CODE2=`curl --write-out "%{http_code}\n" "https://github.com/OpenDRR/${i}/blob/main/LISEZMOI.md" --output /dev/null --silent`
      #   echo $HTTP_CODE2
        done
