name: Check for README.md and LISEZMOI.md

on:
  push:
  workflow_dispatch:

jobs:
  readme-check:
    runs-on: ubuntu-latest
    steps:
    - name: Get list of repos
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        USER: ${{ github.actor }}
      run: |
        result=`curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/orgs/DamonU2/repos`
        echo $result
