name: Check for README.md and LISEZMOI.md

on:
  push:
  workflow_dispatch:

jobs:
  readme-check:
    runs-on: ubuntu-latest
    steps:
    - name: Get list of repos
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        result=`curl -H "Authorization: $TOKEN" -H "Accept: application/vnd.github.v3+json" https://api.github.com/orgs/OpenDRR/repos?per_page=100 | jq .[].name | tr -d \"`
        results=($result)
        for REPO in "${results[@]}"
        do
          echo $REPO
        done
      #echo https://api.github.com/repos/OpenDRR/$REPO/contents/README.md
      #RESPONSE=`curl -i -H "Authorization: $TOKEN" https://api.github.com/repos/OpenDRR/$REPO/contents/README.md --write-out "%{http_code}\n" --output /dev/null --silent`
      #echo $RESPONSE
        
          
      #HTTP_CODE2=`curl --output /dev/null --silent --write-out "%{http_code}\n" https://api.github.com/repos/OpenDRR/$i/contents/LISEZMOI.md`
      #   echo $HTTP_CODE2